### ISSUE TITLE
Edit Account Option

### ISSUE THREAD

**Issue by kirstenfrager** [BinnyK/dynamic-pilgrim#21]
- have an option to "edit account" once user has logged in to update/change their details
- possibly located in navbar if possible for easy access

**Comment by marlbones** [comment]
Thanks for the input, Kirsten. We will be implementing portfolios with the option to edit your account shortly.

**Comment by kirstenfrager** [comment]
i've created a pull request for you to save you the time :)

**Comment by BinnyK** [comment]
Thanks Kirsten. Merged!
