### ISSUE TITLE
Mobile navbar issues

### ISSUE THREAD

**Issue by abazilla** [BinnyK/dynamic-pilgrim#27]
Hi guys,

Really nice app here, appreciating what you've done here. Just a quick one, the top left section of the navbar (Ranking, Feed, FAQ, News) does not appear on mobile devices.

Cheers!
abazilla 
<strong> (Currently Rank #1) </strong>

**Comment by BinnyK** [comment]
Thanks Aba. Nav bar now shows the links. #29
